name: Prepare notebooks for the Google Colab environment

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout colab
        uses: actions/checkout@v2
        with:
          path: colab
          ref: colab
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install the required Python libraries
        run: pip install nbformat
      - name: Save the original commit message
        run: echo ::set-env name=COMMIT_MESSAGE::$(git log -1  --pretty='%s')
      - name: Preprocess notebooks
        run: python tools/prepare_notebooks_for_colab.py --input-dir notebooks --output-dir ${GITHUB_WORKSPACE}/colab
      - name: Commit changes
        run: |
          cd ${GITHUB_WORKSPACE}/colab
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "${COMMIT_MESSAGE}"
      - name: Push changes
        uses: ad-m/github-push-action@fe38f0a751bf9149f0270cc1fe20bf9156854365
        with:
          directory: ${{ github.workspace }}/colab
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: colab
